// <auto-generated />
using System;
using FinalProject1withAngular6.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject1withAngular6.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220305174149_xyz")]
    partial class xyz
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject1withAngular6.Context.Attendance", b =>
                {
                    b.Property<string>("attendanceid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("employeeid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("presenttime")
                        .HasColumnType("datetime2");

                    b.Property<int>("slno")
                        .HasColumnType("int");

                    b.HasKey("attendanceid");

                    b.HasIndex("employeeid");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("FinalProject1withAngular6.Context.Department", b =>
                {
                    b.Property<string>("departmentid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("departmentname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departmentid");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("FinalProject1withAngular6.Context.Employees", b =>
                {
                    b.Property<string>("employeeid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("activesection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departmentid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("joindate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeid");

                    b.HasIndex("departmentid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FinalProject1withAngular6.Context.Attendance", b =>
                {
                    b.HasOne("FinalProject1withAngular6.Context.Employees", "employees")
                        .WithMany("Attendances")
                        .HasForeignKey("employeeid");

                    b.Navigation("employees");
                });

            modelBuilder.Entity("FinalProject1withAngular6.Context.Employees", b =>
                {
                    b.HasOne("FinalProject1withAngular6.Context.Department", "department")
                        .WithMany("employees")
                        .HasForeignKey("departmentid");

                    b.Navigation("department");
                });

            modelBuilder.Entity("FinalProject1withAngular6.Context.Department", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("FinalProject1withAngular6.Context.Employees", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
